[general]
allowedHosts = ["*.fundamentei.io", "*.fundamentei.com", "*.fndm.to", "localhost:*", "localhost", "httpbin.org"]
allowedMethods = ["GET", "POST", "OPTIONS"]
# Use ":0" if you want to bind on the next available port
listen = ":25256"
# This is mainly to avoid recursion
disallowedHosts = ["rproxy.fundamentei.io", "rproxy.fndm.to"]
isEncryptedHeaderKey = "X-Fndm-Is-Encrypted"
sharedKeySalt = "15365230-aa22-4f5f-aa46-f86076a0b6b2"

[limits]
maxConnsPerHost = 0
maxIdleConns = 100
maxIdleConnsPerHost = 2
maxRequestSizeInKb = 10
maxResponseHeaderInKb = 0
maxResponseSizeInKb = 10

[timeouts]
clientTimeout = 30
dialerTimeout = 30
expectContinueTimeout = 10
idleConnTimeout = 90
responseHeaderTimeout = 20
tlsHandshakeTimeout = 10
